### ISSUE TITLE
Nervaluate CLI

### ISSUE THREAD

**Issue by nsorros** [MantisAI/nervaluate#44]
It would be great to be able to trigger `nervaluate` from the command line. Something similar to `spacy evaluate` https://spacy.io/api/cli#evaluate.

We can start with `nervaluate model_path data_path`

**Comment by ivyleavedtoadflax** [comment]
Nice idea. It doesn't actually use a model though, so it would be: `nervaluate predicted_tokens true_tokens` or similar.

**Comment by nsorros** [comment]
It does not know, it will when this is implemented :)

**Comment by ivyleavedtoadflax** [comment]
:+1:

**Comment by nsorros** [comment]
I think the conclusion here was that `nervaluate` should not care about models. If this would move forward maybe it should work on paths like `data_path` and `predicted_data_path` or tokens as Matt suggested

**Comment by ivyleavedtoadflax** [comment]
agree, let's close.
