### ISSUE TITLE
Evaluator accept prodigy model instead of y_true, y_pred

### ISSUE THREAD

**Issue by nsorros** [MantisAI/nervaluate#47]
As Prodigy does not offer a quick command to do precautions, it would be convenient to just be able to pass the data and model to Evaluator and get the metrics instead of having to run a predict script to use the tool.

**Comment by nsorros** [comment]
@ivyleavedtoadflax have I missed something here?

**Comment by ivyleavedtoadflax** [comment]
No, you're right, but in the short term I would prioritise fixing the bugs over implementing a model API

**Comment by nsorros** [comment]
I want to do these improvements so that we can have `cube` using it for evaluation

**Comment by ivyleavedtoadflax** [comment]
agree :+1

**Comment by nsorros** [comment]
I think this will be covered by #44 implemented as described in #49 so closing for now
