### ISSUE TITLE
Why aren't tokens matched?

### ISSUE THREAD

**Issue by vedantc6** [MantisAI/nervaluate#53]
The question might be stupid, but I see there's no actual word given as input in the Prodigy span style.
For an example:

Truth: "Paris" -> [[{"label": "PER", "start": 0, "end": 1}]]
Pred: "London" -> [[{"label": "PER", "start": 0, "end": 1}]]

The evaluation shouldn't have Precision, Recall and F1 as 1.0 but it does. Even if I change the format to conll style, it is of no use.

Am I missing something?

![image](https://user-images.githubusercontent.com/15234578/130481982-0de5b61d-21bf-406f-accd-3ab6a8159f50.png)

**Comment by ivyleavedtoadflax** [comment]
Hi @vedantc6, thanks for raising an issue. I think you are using the tool for a use that it was not intended to meet. The tool is for comparing sets of annotations on the same input document. It simply will not function when the input documents are different (as you have found).

**Comment by ivyleavedtoadflax** [comment]
Assuming this is stale, and closing.
