### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/nervaluate#56]
@davidsbatista I see you changed the original code that this is based on into an MIT license. I propose doing the same here. Is that ok with everyone who has contributed?

@davidsbatista @lizgil @aflueckiger @pimmeerdink 

cc @nsorros

**Comment by davidsbatista** [comment]
go ahead, I'm OK with it 👍🏽

**Comment by aflueckiger** [comment]
That’s fine with me as well.

**Comment by pimmeerdink** [comment]
go for it!
