### ISSUE TITLE
More information about output?

### ISSUE THREAD

**Issue by abhibha1807** [MantisAI/nervaluate#68]
Is there a way to find out for which instance during evaluation was marked under 'correct' or 'incorrect' or 'spurious', etc for a particular evaluation schema?

**Comment by vmenger** [comment]
I would also be interested in this, so false positives/negatives can be analyzed further. On a first glance, this seems like it would be straightforward to implement, by modifying `compute_metrics` to add the annotation in a separate list anytime it increments a counter. 

To the maintainers: is this something you would consider adding? I can do a PR.

**Comment by ivyleavedtoadflax** [comment]
Hi @abhibha1807 @vmenger thanks for your comments. Please feel free to PR @vmenger and we will review :pray:

**Comment by davidsbatista** [comment]
Hi @jackboyla, and thanks a lot for you collaboration.

Please don't use `self.results` to store the indices, define another structure. I believe this should be done in a different structure to keep things clean and separate; this might also reduce the number of failed tests. Maybe you can follow the same philosophy as in `self.results`, i.e, define a base dictionary and then use `deepcopy`.

Going back to the original issue:

``Is there a way to find out for which instance during evaluation was marked under 'correct' or 'incorrect' or 'spurious', etc for a particular evaluation schema?``

 I see that the question was to have a way to find which instances were marked under correct, incorrect, spurious, etc.

Maybe it's also useful to have a function that prints a nice output to the console with those entities, just as indices, but optionally if the text is given text surface strings themselves.

What do you think @ivyleavedtoadflax ?

By the way, late happy New Year to you all :)
