### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by mrshu** [MantisAI/nervaluate#77]
First of all, thank you for a very nice evaluation package!

When I was playing with it, my first instinct was to install it from PyPI (https://pypi.org/project/nervaluate/) but it seems the version there (`0.1.8`) is rather old (released in 2020) compared to the current version in the `master` branch (`0.2.0`).

Do you think it would be possible to update the PyPI package by any chance?

Thanks!

**Comment by ivyleavedtoadflax** [comment]
Done!
